### ISSUE TITLE
amazon world book day - but only for a few days

### ISSUE THREAD

**Issue by wireguy** [quality-quarantine/quality-quarantine.github.io#7]
https://www.amazon.com/article/read-the-world-2020?pldnSite=1

@todrobbins 

9 free kindle books, but only for a few days

**Comment by todrobbins** [comment]
✅ [added](https://github.com/quality-quarantine/quality-quarantine.github.io/commit/5c12d26be519af24cbdd7592b6c91bd6597f6b43)
